// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCM1Bip0oZ0g07GEoLGaPyo5vo-VgSR-7U',
    appId: '1:873706972428:web:6e17a57ca1451af332d529',
    messagingSenderId: '873706972428',
    projectId: 'builmeet',
    authDomain: 'builmeet.firebaseapp.com',
    storageBucket: 'builmeet.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPFXIHAB-X-OIe0Heu5GR7gN38rBcM-m8',
    appId: '1:873706972428:android:9330eec8e443c5d832d529',
    messagingSenderId: '873706972428',
    projectId: 'builmeet',
    storageBucket: 'builmeet.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUCG4qBeueUSgh6p84L1aE5foximeS6JI',
    appId: '1:873706972428:ios:14d034c6c154719832d529',
    messagingSenderId: '873706972428',
    projectId: 'builmeet',
    storageBucket: 'builmeet.appspot.com',
    iosBundleId: 'com.builmeet.builmeet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUCG4qBeueUSgh6p84L1aE5foximeS6JI',
    appId: '1:873706972428:ios:14d034c6c154719832d529',
    messagingSenderId: '873706972428',
    projectId: 'builmeet',
    storageBucket: 'builmeet.appspot.com',
    iosBundleId: 'com.builmeet.builmeet',
  );
}
